# Generated by Django 5.0 on 2023-12-06 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="route",
            options={"ordering": ["source"]},
        ),
    ]
