# Generated by Django 5.0 on 2023-12-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0006_airplane_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airport",
            options={"ordering": ["name"]},
        ),
        migrations.AddConstraint(
            model_name="route",
            constraint=models.UniqueConstraint(
                fields=("source", "destination"), name="unique_route"
            ),
        ),
    ]
